server:
    port: 3000


zuul:
    routes:
        service-1:
            path: /order/**
            serviceId: service-1

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:4000/eureka/
spring:
    application:
        name: api-gateway